"""Single source of truth for gesture labels, GPIO pins, and command translations."""

GESTURE_LABELS = [
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J",
    "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T",
    "U", "V", "W", "X", "Y", "Z",
    "OK", "STOP", "HELP", "THANK_YOU",
]

GESTURE_PIN_MAP = {
    "A":         17,
    "B":         27,
    "C":         22,
    "D":          5,
    "E":          0,
    "F":          0,
    "G":          0,
    "H":          0,
    "I":          0,
    "J":          0,
    "K":          0,
    "L":          6,
    "M":          0,
    "N":          0,
    "O":          0,
    "P":          0,
    "Q":          0,
    "R":          0,
    "S":          0,
    "T":          0,
    "U":          0,
    "V":          0,
    "W":          0,
    "X":          0,
    "Y":         13,
    "Z":          0,
    "OK":        24,
    "STOP":      19,
    "HELP":      26,
    "THANK_YOU": 21,
}

COMMAND_MAP = {
    "A":         "LETTER_A",
    "B":         "LETTER_B",
    "C":         "LETTER_C",
    "D":         "LETTER_D",
    "E":         "LETTER_E",
    "F":         "LETTER_F",
    "G":         "LETTER_G",
    "H":         "LETTER_H",
    "I":         "LETTER_I",
    "J":         "LETTER_J",
    "K":         "LETTER_K",
    "L":         "LETTER_L",
    "M":         "LETTER_M",
    "N":         "LETTER_N",
    "O":         "LETTER_O",
    "P":         "LETTER_P",
    "Q":         "LETTER_Q",
    "R":         "LETTER_R",
    "S":         "LETTER_S",
    "T":         "LETTER_T",
    "U":         "LETTER_U",
    "V":         "LETTER_V",
    "W":         "LETTER_W",
    "X":         "LETTER_X",
    "Y":         "LETTER_Y",
    "Z":         "LETTER_Z",
    "OK":        "OK",
    "STOP":      "STOP",
    "HELP":      "HELP",
    "THANK_YOU": "THANKS",
}
